import React from 'react'

import { ClientProvider } from '@/core/providers/ClientProvider'
import type { Metadata } from 'next'

import '../styles/globals.scss'

export const metadata: Metadata = {
    title: 'Lincode skills',
    description: 'Generated by lincode ',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body>
                <ClientProvider>{children}</ClientProvider>
            </body>
        </html>
    )
}
